sonar.projectKey=faker19angular_develop
sonar.projectName=Faker 19 Angular (Develop)
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000

# Exclusions (optional)
sonar.sources=src
sonar.exclusions=**/*.spec.ts,**/*.module.ts,**/node_modules/**,**/dist/**

# Test settings (optional)
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.typescript.lcov.reportPaths=coverage/lcov.info

# Disable SCM detection to avoid unnecessary warnings
sonar.scm.disabled=true
