sonar.projectKey=faker19angular
sonar.projectName=Faker 19 Angular
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
sonar.branch.name=develop  # Set develop as the branch to analyze

# Exclusions (for test files, modules, and build-related files)
sonar.sources=src
sonar.exclusions=**/*.spec.ts,**/*.module.ts,**/node_modules/**,**/dist/**

# Set the test files and coverage report (if using Jest or Karma)
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.typescript.lcov.reportPaths=coverage/lcov.info

# SCM detection (set to false if you don't need it)
sonar.scm.disabled=true
