sonar.projectKey=faker19angular
sonar.projectName=Faker 19 Angular
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
sonar.token=sqa_fee3bb6e8a4f728c4ae15320d4f108ed96a642bc

# Exclusions (Optional)
sonar.sources=src
sonar.exclusions=**/*.spec.ts, **/*.module.ts, **/node_modules/**, **/dist/**


# sqa_fee3bb6e8a4f728c4ae15320d4f108ed96a642bc
